---
- name: Create dir for postgres_exporter
  file:
   path: /data/postgres_exporter/
   owner: postgres
   group: postgres
   state: directory
   mode: '0770'

- name: Download and extract archive
  unarchive:
    src: "{{ PGEXP_ARCH_URL }}"
    dest: /data/postgres_exporter/
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: 0776

- name: Copy postgres_exporter service file
  template:
    src: templates/postgres_exporter.j2
    dest: /etc/systemd/system/postgres_exporter.service
# Чекни права и владельца

- name: Copy metrics file
  copy:
    src: files/metrics.yaml
    dest: /var/lib/pgsql/
    owner: postgres
    group: postgres

- name: Make sure a service unit postgres_exporter is running
  systemd:
    state: started
    name: postgres_exporter
    enabled: yes
    daemon_reload: yes