---
- name: Enable postgres_exporter port in firewalld
  firewalld:
    permanent: yes
    port: 9187/tcp
    state: enabled

- name: Create dir for exporters
  file:
   path: "{{ item }}"
   owner: postgres
   group: postgres
   state: directory
   mode: '0770'
  loop:
   - /var/lib/pgsql/exporters
   - /var/lib/pgsql/exporters/postgres_exporter

- name: Download and extract archive
  unarchive:
    src: http://binary.moscow.alfaintra.net/artifactory/generic-postgresql-materials/postgres_exporter/bin/postgres_exporter-0.10.0.linux-amd64.tar
    dest: /var/lib/pgsql/exporters/postgres_exporter/
    remote_src: yes
    extra_opts: [--strip-components=1]
    mode: 0776

- name: Copy postgres_exporter service file
  template:
    src: templates/postgres_exporter.j2
    dest: /etc/systemd/system/postgres_exporter.service
# Чекни права и владельца

- name: Copy metrics file
  copy:
    src: files/metrics.yaml
    dest: /var/lib/pgsql/exporters/postgres_exporter/
    owner: postgres
    group: postgres

- name: Make sure a service unit postgres_exporter is running
  systemd:
    state: started
    name: postgres_exporter
    enabled: yes
    daemon_reload: yes