---
- name: Install openssl11-libs with YUM
  package:
    name: openssl11-libs
    state: latest

- name: Enable Odyssey port in firewalld
  firewalld:
    permanent: yes
    port: "{{ PG_ODYSSEY_PORT }}/tcp"
    state: enabled

- name: Create dir for Odyssey
  file:
    path: /data/odyssey/
    owner: postgres
    group: postgres
    state: directory
    mode: '0770'

- name: Extract archive
  unarchive:
    src: "http://binary.moscow.alfaintra.net/artifactory/generic-postgresql-materials/odyssey/bin/1.1/odyssey.linux-amd64.1.0.tar.gz"
    dest: /data/odyssey
    remote_src: yes
    mode: 0776
    owner: postgres
    group: postgres
    
- name: Generate Odyssey config file
  template:
    src: templates/odyssey.j2
    dest: /data/odyssey/odyssey.conf
    mode: '0760'
    owner: postgres
    group: postgres
    newline_sequence: '\n'

- name: Start odyssey
  command: /data/odyssey/odyssey /data/odyssey/odyssey.conf
  become: true
  become_user: postgres