---
- name: install Filebeat rpm with YUM
  package:
    name: "{{ FILEBEAT_RPM_URL }}"
    state: present

- name: Generate postgresql_module config file
  template:
    src: templates/postgresql_filebeat.j2
    dest: /etc/filebeat/modules.d/postgresql.yml.disabled
    mode: '0644'
    owner: root
    group: root

- name: Generate filebeat config file
  template:
    src: templates/filebeat.j2
    dest: /etc/filebeat/filebeat.yml
    mode: '0600'
    owner: root
    group: root

- name: Enabled postgresql module
  command: filebeat modules enable postgresql
    
- name: Make sure a service unit filebeat is running
  systemd:
    state: started
    name: filebeat
    enabled: yes
    daemon_reload: yes