---
- name: Disable SELinux
  selinux:
    state: disabled
  notify: Reboot machine

- name: Enable PostgreSQL port in firewalld
  firewalld:
    permanent: yes
    port: "{{ PG_PORT }}/tcp"
    state: enabled

- name: install langpack for RedHat-based 8.*
  package:
    name: "glibc-langpack-ru"
    state: present
  when:
    - ansible_facts['os_familhy'] == "RedHat" 
    - ansible_facts['distribution_major_version'] == "8"